import{BadRequestException,Injectable}from'@nestjs/common';import{InjectModel}from'@nestjs/mongoose';import{Model,Types}from'mongoose';import{createHash,randomUUID}from'crypto';import{PlansService}from'../plans/plans.service';import{SubscriptionsService}from'../subscriptions/subscriptions.service';import{Payment,PaymentDocument}from'./payment.schema';
@Injectable()export class PaymentsService{constructor(@InjectModel(Payment.name)private model:Model<PaymentDocument>,private plans:PlansService,private subs:SubscriptionsService){}
 async checkout(userId:string,planId:string){const plan:any=await this.plans.get(planId);if(!plan.active)throw new BadRequestException('Plan inactivo');const sub:any=await this.subs.createPending(userId,planId,plan.price,plan.durationDays);const reference=`GK-${Date.now()}-${randomUUID().slice(0,8)}`;const p=await this.model.create({userId:new Types.ObjectId(userId),planId:new Types.ObjectId(planId),subscriptionId:sub._id,reference,amount:plan.price,currency:'COP',paymentMethod:'ONLINE',concept:plan.name});const amountInCents=Math.round(plan.price*100);const integrity=process.env.WOMPI_INTEGRITY_SECRET;const signature=integrity?createHash('sha256').update(`${reference}${amountInCents}COP${integrity}`).digest('hex'):'';return{paymentId:p._id,subscriptionId:sub._id,reference,amount:plan.price,amountInCents,currency:'COP',mode:process.env.PAYMENTS_MODE||'mock',wompi:{publicKey:process.env.WOMPI_PUBLIC_KEY||'',signature,redirectUrl:process.env.WOMPI_REDIRECT_URL||'http://localhost:3000/dashboard'}};}
 async mockApprove(userId:string,paymentId:string){if((process.env.PAYMENTS_MODE||'mock')!=='mock')throw new BadRequestException('Mock deshabilitado');const p:any=await this.model.findOne({_id:paymentId,userId});if(!p)throw new BadRequestException('Pago no encontrado');p.status='APPROVED';await p.save();await this.subs.activate(String(p.subscriptionId));return p;}
 private pathValue(root:any,path:string){return path.split('.').reduce((v,k)=>v?.[k],root);}
 async webhook(body:any,headerChecksum?:string){const secret=process.env.WOMPI_EVENTS_SECRET;if(secret){const props=body?.signature?.properties||[];const raw=props.map((p:string)=>String(this.pathValue(body?.data,p)??'')).join('')+String(body?.timestamp??'')+secret;const calculated=createHash('sha256').update(raw).digest('hex');const received=(headerChecksum||body?.signature?.checksum||'').toLowerCase();if(!received||calculated.toLowerCase()!==received)throw new BadRequestException('Firma de evento Wompi inválida');}const tx=body?.data?.transaction;if(!tx?.reference)return{received:true};const p:any=await this.model.findOne({reference:tx.reference});if(!p)return{received:true};p.status=tx.status||p.status;p.providerTransactionId=tx.id||'';await p.save();if(tx.status==='APPROVED')await this.subs.activate(String(p.subscriptionId));return{received:true};}
 async list(){return this.model.find().populate('userId','name email').populate('planId','name').sort({createdAt:-1}).lean();}
 async recordCash(data:any){if(!data.userId||!data.amount)throw new BadRequestException('userId y amount son obligatorios');return this.model.create({userId:new Types.ObjectId(data.userId),amount:Number(data.amount),reference:`CASH-${Date.now()}-${randomUUID().slice(0,8)}`,currency:'COP',paymentMethod:'CASH',concept:data.concept||'Pago en efectivo',status:'APPROVED'});}
 async revenue(){const r=await this.model.aggregate([{$match:{status:'APPROVED'}},{$group:{_id:null,total:{$sum:'$amount'}}}]);return r[0]?.total||0;}
 async weeklyRevenue(){const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-start.getDay()+1);const r=await this.model.aggregate([{$match:{status:'APPROVED',paidAt:{$gte:start}}},{$group:{_id:null,total:{$sum:'$amount'}}}]);return r[0]?.total||0;}}
